// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bykljyggtnhwumfcwdwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5a2xqeWdndG5od3VtZmN3ZHd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNTI3ODUsImV4cCI6MjA3NDYyODc4NX0.NZ8R1vQ1tHUPFpJT74-LhYJZEQFwZma_N4YHmTNi28o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});